### PR TITLE
Twf.authentication

### LINKED ISSUE #25: feature: log in - happy
As a user, when I submit a valid username and password on the welcome page, I am taken to my user dashboard where I see a button to log out.

### LINKED ISSUE #26: feature: log in - sad
as a user, when I log in with incorrect credentials,
I am redirected to the welcome page
and I see a flash message indicating that my credentials were not valid
I am not logged in

### PR DESCRIPTION
**Pull request by twarbelow**
### Description:
logging in logic
TODO notes

### All Submissions:

* [ ] Have you linked this PR to a card in the project board?
* [ ] Have you tagged a reviewer?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Does your submission pass rubocop
3. [ ] Does your submission pass TravisCI

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: spec/features/welcome/index_spec.rb [hunk 1]
```diff
@@ -5,16 +5,19 @@
...
-  it 'displays application description' do
-    expect(page).to have_content(@description)
-  end
+# TODO - define description before expectation
+  # it 'displays application description' do
+  #   expect(page).to have_content(@description)
+  # end
 
   it 'displays login fields for username and password' do
-    page.has_field?('Username', type: 'username')
```
Comment (JBrabson) [inline spec/features/welcome/index_spec.rb:17]: If you run on your comp... and have it as expect(page).to have_field('username)... do you have issue? I typically use that syntax but it was failing across the board. Found this, and seemed ot have passed (alas, I was wrong). Thoughts?

Comment (twarbelow) [reply spec/features/welcome/index_spec.rb:17]: mine worked alright with that syntax...weird that it doesn't work for you!

Comment (twarbelow) [reply spec/features/welcome/index_spec.rb:17]: this test is not performing as expected though. Going to go look at it now.
